### ISSUE TITLE
"No backend available" error, *I'm a python beginner*

### ISSUE THREAD

**Issue by niallodowd** [SivyerLab/pyCrafter4500#11]
Hi There,

I'm having issues simply getting initial commands through to my DLP350 LC4500. I was able to pip install pycrafter4500, and import it successfully, but when I call pycrafter4500.power_up() I get the error:

Traceback (most recent call last):

  File "<ipython-input-2-08c5317d7bd7>", line 1, in <module>
    pycrafter4500.power_up()

  File "C:\ProgramData\Anaconda3\lib\site-packages\pycrafter4500\pycrafter4500.py", line 574, in power_up
    with connect_usb() as lcr:

  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pycrafter4500\pycrafter4500.py", line 87, in connect_usb
    device = usb.core.find(idVendor=0x0451, idProduct=0x6401)

  File "C:\ProgramData\Anaconda3\lib\site-packages\usb\core.py", line 1299, in find
    raise NoBackendError('No backend available')

NoBackendError: No backend available

I'm convinced that this issue may be trivial for this community, so please help me!
Thanks so much!

**Comment by niallodowd** [comment]
Fixed the issue by following https://stackoverflow.com/questions/33972145/pyusb-on-windows-8-1-no-backend-available-how-to-install-libusb

!!
